-- ========== GENERATED BY BuildingTemplate Editor (Ctrl-Alt-B) DO NOT EDIT MANUALLY! ==========

UndefineClass('RMR_Micro_G_Lab')
DefineClass.RMR_Micro_G_Lab = {
	__parents = { "ScienceInstitute" },
	__generated_by_class = "ModItemBuildingTemplate",


	mod_handle = 1,
	object_class = "ScienceInstitute",
	construction_cost_Metals = 15000,
	construction_cost_Electronics = 34000,
	construction_cost_WasteRock = 36000,
	dome_required = false,
	dome_forbidden = true,
	can_refab = false,
	cargo_prefab = false,
	maintenance_resource_amount = 6000,
	consumption_resource_type = "PreciousMinerals",
	consumption_max_storage = 10000,
	consumption_amount = 2000,
	consumption_type = 5,
	display_name = T(976666971700, --[[ModItemBuildingTemplate RMR_Micro_G_Lab display_name]] "Micro-G Lab"),
	display_name_twolines = T(794802965401, --[[ModItemBuildingTemplate RMR_Micro_G_Lab display_name_twolines]] "Micro-G Lab"),
	display_name_pl = T(824345575088, --[[ModItemBuildingTemplate RMR_Micro_G_Lab display_name_pl]] "Micro-G Labs"),
	description = T(422069162771, --[[ModItemBuildingTemplate RMR_Micro_G_Lab description]] "Radiation hardened micro-G research lab."),
	build_category = "MicroGMannedExtractors",
	display_icon = "UI/IconsRemaster/Buildings/lowg_lab.png",
	entity = "LowGLab",
	label1 = "OutsideBuildings",
	demolish_sinking = range(15, 30),
	disabled_in_environment = set( "Surface", "Underground" ),
	alt_entity_2_sponsor = {},
	electricity_consumption = 34000,
	max_workers = 12,
	persist_baseclass = "ScienceInstitute",
}

