return PlaceObj('ModDef', {
    'title', "Hard Rebalance Patch (Realistic Mars Relaunched)",
    'description', "[h2]Welcome to Mars.[/h2]\n\nThis is an updated [url=https://steamcommunity.com/sharedfiles/filedetails/?id=1339570684]Realistic Mars[/url] for Surviving Mars: Relaunched.\n\nRealistic Mars Relaunched aims to recreate survival on a hostile red planet. Sound infrastructure and logistics are required merely to persist here, still more to turn the wrathful god of war into the jewel of the solar system.\n\n[h2]Features[/h2]\n\n[b]Power[/b]\nSolar arrays accumulate dust and lose output. Wind is not a dependable servant. Accumulators return less energy than was stored. The grid must be sized for the worst hour, or the colony will suffer blackouts. The environment is unkind to reserves.\n\n[b]Research[/b]\nA vast research campus is not feasible on an early colony. Scientific capacity on Mars is deliberately scarce. Demand for zero-gravity work in the private sector is high. Additional laboratories belong where gravity releases its hold.\n\n[b]Underground[/b]\nThe surface remains a short hour from disaster. Sensitive equipment will not be certified in the open until the air can be trusted. The most vulnerable colonists refuse that risk. Nearby lava caves offer a roof and almost nothing worth digging. A shelter is not a mine.\nBEWARE: Factories can only be built underground!\n\n[b]Resources[/b]\nMars does not lay its wealth at your feet. The good veins want looking for: survey teams, a stretch of rail, perhaps a haul from some nameless rock in the black.\n\n[b]Wonders[/b]\nA wonder is familiar technology in ceremonial dress. The Telescope is an expensive pair of eyes. The Mohole is a mine that does not empty and does not cease to consume power and labour. Both are useful. Neither is, by default, the wiser expenditure.\n\n[b]Terraforming[/b]\nThe work will not do itself. Terraforming will fight your industry, your export, and expansion for the same scarce resources. Countless times the colony will have to choose between growth, independence, exports, and greenery before the first rain falls on Mars.\n\n[b]Laws[/b]\nMars was sold as a frontier without clerks or filing cabinets. The colonists believed that. A short law book still feels like freedom. A working Assembly and its ministries can carry a few more pages.\n\n[b]Factions[/b]\nPolitics does not stop at the chamber door. Supporters live with their faction’s mood. Content does nothing. Happy raises comfort and morale a little. Discontent cuts both. At breaking point they also lose sanity, and Earthborn may turn Earthsick. A working Assembly moves the effect one step toward the good.\n\n[b]Prefabs[/b]\nEarth will still sell you a building in a crate. It will not undercut a colony that already mines and machines the same parts.\n\n[b]Sponsors[/b]\nStarting cash and rockets follow the size of the real programs. The International Mars Mission still has the largest cheque. NASA lives on a smaller pile plus a modest stipend from Earth. Europe and India start poorer; they make it up in research and cheap construction. Unique rockets, buildings, and drawbacks stay.\n\n[b]Rivals & Global Support[/b]\nRival colonies follow Assembly standing and their own tempers. Cargo sent their way can raise standing. A neighbour that holds you in high regard will open its Earth catalog: unique prefabs and hardware, sold at a premium. You buy the crate, not the blueprint.\n\n[b]Logistics[/b]\nEarth is farther than the brochures claimed. Transit takes longer. Sponsor funding is a little short of the advertised sum. Rare metals fetch a little less.\n\n[h2]Options[/h2]\nEach of these systems may be switched off in the mod options. A Colony Briefing on a new map names the ones that are currently in force.",
    'short_description', "This is a hard rebalance of Surviving Mars: Relaunched.\n\nhttps://steamcommunity.com/sharedfiles/filedetails/?id=3799940855\n\nAll features will be listed at colony start and in the Mod Options.",
    'image', "Mod/JTTAEkH/Images/Starman.jpg",
    'last_changes', "Micro-G Lab: only buildable on asteroids.\nFaction Screen: Mars and Earth factions, supporter counts.\nEarth Factions button on the Rival POI screen.\nFaction Rebalance: faction mood now reaches individual colonists.\nSponsor Rebalance: starting funds and rockets follow real program size. NASA stipend 50M.\nProject Spawn: Magnetic Shield and Mirror repair fixed; projects require crew again.",
    'id', "JTTAEkH",
    'author', "Spannbeton",
    'version_major', 1,
    'version_minor', 10,
    'version', 77,
    'lua_revision', 350453,
    'saved_with_revision', 403908,
    'restart_on_unload', true,
    'code', {
        "Code/Solar Rebalance.lua",
        "Code/Wind Rebalance.lua",
        "Code/Battery Rebalance.lua",
        "Code/Research Rebalance.lua",
        "Code/BuildingTemplate/RMR_Micro_G_Lab.generated.lua",
        "Code/BB Rebalance.lua",
        "Code/Resource Rebalance.lua",
        "Code/Wonder Rebalance.lua",
        "Code/Terraforming Rebalance.lua",
        "Code/Terraforming Projects.lua",
        "Code/Messages.lua",
        "Code/Law Rebalance.lua",
        "Code/Prefab Rebalance.lua",
        "Code/Misc Settings.lua",
        "Code/Rival Rebalance.lua",
        "Code/Rival UI.lua",
        "Code/Rival POI.lua",
        "Code/Faction Screen.lua",
        "Code/Faction Rebalance.lua",
        "Code/Sponsor Rebalance.lua",
    },
    'default_options', {
        Battery_Rebalance = true,
        Export_Price_Delta = -2,
        Faction_Rebalance = true,
        Flight_Time_Mult = 2,
        Free_Laws = 4,
        Free_Laws_Assembly = 2,
        Free_Laws_Ministry = 1,
        Funding_Percent = 100,
        Law_Rebalance = true,
        Laws_Comfort_Penalty = 2,
        Laws_Sanity_Penalty = 1,
        Power_Loss = 50,
        Prefab_Rebalance = true,
        Research_Rebalance = true,
        Resource_Concrete_MaxAmount = 800,
        Resource_Concrete_Patches = 12,
        Resource_Metals_DeepDeposits = 1,
        Resource_Metals_MaxAmount = 10000,
        Resource_Metals_NormalDeposits = 2,
        Resource_PreciousMetals_DeepDeposits = 1,
        Resource_PreciousMetals_MaxAmount = 5000,
        Resource_PreciousMetals_NormalDeposits = 2,
        Resource_Rebalance = true,
        Resource_Water_DeepDeposits = 2,
        Resource_Water_MaxAmount = 40000,
        Resource_Water_NormalDeposits = 3,
        Rival_Rebalance = true,
        Rival_Sabotage = true,
        Solar_BaseMult = 100,
        Solar_Rebalance = true,
        Sponsor_Rebalance = true,
        Terraforming_Rebalance = true,
        Underground_Rebalance = true,
        Wind_Amplitude = 50,
        Wind_Gusts = 40,
        Wind_Minimum = 30,
        Wind_Periodicity = 32,
        Wind_Rebalance = true,
        Wonder_Rebalance = true,
    },
    'has_data', true,
    'saved', 1789587555,
    'code_hash', -6101138114395284819,
    'affected_resources', {
        PlaceObj('ModResourcePreset', {
            'Class', "BuildingTemplate",
            'Id', "RMR_Micro_G_Lab",
            'ClassDisplayName', "Building Template",
        }),
    },
    'pdx_id', 158808,
    'pdx_version', "3",
    'steam_id', "3799940855",
    'TagGameplay', true,
    'TagOther', true,
})